// Wait! Let's look at api/generate.js again:
/*
    let accumulated = '';
    let questionsSent = 0;

    for await (const chunk of stream) {
      const text = chunk.text;
      if (text) {
        accumulated += text;

        // Extract all fully-formed question objects so far
        const parsed = extractCompleteObjects(accumulated);

        // Emit any newly completed questions
        while (questionsSent < parsed.length) {
          if (questionsSent < remainingCount) {
            res.write(`data: ${JSON.stringify({ type: 'question', data: parsed[questionsSent] })}\n\n`);
          }
          questionsSent++;
        }
      }
    }

    res.write(`data: ${JSON.stringify({ type: 'done' })}\n\n`);
    res.end();
*/

// If `parsed.length` becomes 5.
// `questionsSent` goes from 0 up to 4.
// Wait! `remainingCount` was decremented if `pregeneratedQuestion` was used!
// `let remainingCount = count;` -> 5.
// `if (pregeneratedQuestion) { remainingCount = count - 1; }` -> 4.

// So `remainingCount` is 4!
// `if (questionsSent < remainingCount)`
// If `questionsSent` is 4, 4 < 4 is FALSE.
// So `parsed[4]` (the 5th question generated by LLM) is NEVER EMITTED!
// BUT WAIT!
// The LLM is prompted to generate EXACTLY 4 problems:
// `let prompt = \`Generate exactly ${remainingCount} ${subject} problems.\``
// So the LLM SHOULD only generate 4.
// If the LLM generates exactly 4, `parsed.length` is 4.
// `questionsSent` goes 0, 1, 2, 3.
// 0 < 4, 1 < 4, 2 < 4, 3 < 4. They ALL get emitted.
// Then the total emitted is 1 (pregenerated) + 4 (LLM) = 5.

// WHAT IF `pregeneratedQuestion` is null?
// `remainingCount` is 5.
// The LLM is prompted to generate 5 problems.
// It generates 5 problems.
// `parsed.length` is 5.
// `questionsSent` goes 0, 1, 2, 3, 4.
// All 5 get emitted.
